[[DocCompatibility]]
== Compatibility

=== Compatibility of BCD-UI

As of 2022, BCD-UI works without modifications within the following environments

.Server
* JDK 11+
* Tomcat 8.5+ and other servers with Jakarta EE web profile

.Browser
* Recent Edge, Firefox, Safari and Chrome versions
* Internet Explorer 11

.Database
* Oracle 11+
* Postgres 10+
* SQLServer 2016+
* Teradata 10+ in EnterpriseEdition
* MySQL with limitations, please contact BusinessCode

.It makes use of current versions of technologies and specs
* Java Jakarta EE web profile, JDBC, Servlet, JAXB and optionally JSP
* ECMA/JS, DHTML, CSS, HTML, JSON and SVG
* XML, XSLT, XPath and XSD
* Ajax, webservices, XForms architecture and EXSLT
* Apache commons, jQuery and various other open source libraries
* Gradle, Eclipse and IntelliJ IDEA, git

=== Developing for specific browsers

==== Known browser limitations

* favicon.ico is picked up by FireFox when found in webapp root, ie does not do this
* IE does not allow setting the name attribute via DOM (helper function in corePackage.js)
* FireFox throws exception when writing <input>text</input>, this is in sync with the specs
* IE ignores overflow when filter is set in css
* IE: innerHTML (used by renderer) for <script> and <style> tags require both to start with a scoped element, like  `<input type="hidden"/><script defer="false"...`, and the script tag in addition requires an `defer="false"` attribute
* IE has a maximum URL length of 2083 bytes, others do not. When copying URLs from other browsers, they may be less compressed (because it was not necessary), so they may be too long.
* FireFox: the bookmarks created with the bookmark tag open in a sidebar window by default, unless the bookmark property is adjusted manually by the user or if the bookmark is opened in a new tag
* Chrome/WebKit: don't support bookmark via JavaScript at all
* IE seems to handle position() in xsl:key/@match expressions wrong. Sample: match="/*/Something[@pos&gt;3][position()&lt;2]". It will find an empty list instead of a list with two elements.
* Due to a well-known bug in FireFox (at-least 10-24), you need to enable 3rd-party cookies or better add an exception for a webpage with BCD-UI. This flag is per default off ("disabled") since version 22.

==== Working with webkit browsers

Webkit/Chromium based browsers like Edge, Safari, Chrome and Opera compatibility requires the following to be taken into account

* Declare all namespaces used by XSLT, since documents addressed via document() and xsl:import are included in the host XSLT and
elements with undeclared namespaces inherit the default namespace of the (possibly generated) host XSLT
* When using createElementWithPrototype or similar, always work with an explicit namespace, do not use the empty namespace. 
* xsl:include is not supported (use xsl:import instead)
* xsl:apply-imports is not supported. (normally xsl:apply-templates will be sufficient)
* when using xsl:sort, you are limited to use up to 15 successive ones
* Do not use msxml:node-set(), declare and use exslt:node-set() even for IE.
* When generating XSLT with the help of XSLT, use 'generateXSLT' as the generation mode
* When generating XSLT and matching on an input template XSLT, be aware that those elements do not have xsl as namespace
because they are embedded, use select="*[local-name()='output']" and so on instead.
Also do not copy such elements into the output as they would keep the non-xsl namespace,
create these elements with <xsl:element name="output" namespace="http://www.w3.org/1999/XSL/Transform"/> instead
* For webkit it is not allowed to use variables in template match attributes, like <xsl:template match="*[@attr=$myVar/Values]">..
* When a node is provided to the XSLT processor as input, that node becomes the document root, for Gecko and IE "/" remains the root.
* Mix of constant strings and AVT (Attribute Value Template) is not allowed. So use attr="{concat('abc ', $var)}" instead of attr="abc {$var}" for webkit."
* For Webkit the imports are resolved by BCD-UI. This is done by including the imported stylesheet leaving out templates with the same
@match/@name and @mode values for which already a template in the importing stylesheet exists.
But since the others are included then an imported template with match="ns:E[@a]" will win over a template with match="ns:E" existing in the
importing stylesheet. This will let Webkit behave differently than other browsers. Make sure to prevent this situation by defining
exact matching templates in the importing stylesheet.
* It is much faster if in wrs:C[indexExpr] indexExpr is a plain number (a variable holding a number) than an expression. Move such an expression to a helper variable.
* Large documents slow Webkit down. Only provide the part of large documents, if possible.
Use xsl:stylesheet/@bcdxml:wrsHeaderIsEnough to minimize the input for example for generating stylesheets only needed the header.
* All known namespace declarations are repeated on the highest node of each subtree of explicitly written elements.
For example <wrs:C/> will hold all such namespace-nodes if all elements above are created via xsl:element or xsl:copy.
As a workaround, write the root node (in this case wrs:Wrs) also explicitly <wrs:Wrs>...</wrs:Wrs>, then this is the highest, and they will ony
appear once. This improves performance, because Webkit is sensitive against documents with a large serialization representation.

