[[DocCoreArtifacts]]
== Core concepts of BCD-UI

=== Using BCD-UI

==== Page core components

The following components are core on the client side of BCD-UI. They follow the well-known Model/View/Control architecture:

DataProvider:: DataProviders are client side _models_ containing the data of the client, like reporting data, reference data and data reflecting user selections.
On the client, models store their data per default as XML documents, on server side data is stored in a relational database.
Models provide options for loading and changing data, informing listener about changes and saving data back to the server. Data is loaded lazily, i.e. only once it is needed.
Renderer:: Renderers are the _views_ providing the visual parts of the application like reports, edit grids, charts or widgets.
Renderer are implemented in XSLT, JavaScript or doT.js, taking a DataProvider as input and output HTML which is placed on the page.
The default renderer outputs data as a table and can be extended or replace by custom logic.
Controller:: The controller reacts on user interaction, like a button click or a drag and drop activity.
Controllers are small chunks of code implemented in JavaScript.
This code can be provided by the BCD-UI library or by the project.
Not only user interaction but also events thrown by models loading and changing can be used to trigger a controller.
Widgets:: Widgets are small views for user information and interaction like input fields, the menu and fly-overs.
Widgets store their status per default in a page-wide _guiStatus_ to make it and change events centrally available for all parts of the page.
Components:: Components are more complex views, for example cubes or charts, usually requiring a configuration XML.
Components in most cases consist of multiple views and widgets working together.
Page infrastructure:: Page infrastructure comprises the guiStatus, mechanisms for object life-cycle etc.
The guiStatus is the default model for all widgets and client-side status
and thus usually contains all selections done by the user.
Data requests use the guiStatus to decide which data to retrieve.
This infrastructure also covers generic tasks like client side exports or fly-overs.
Page layout structure:: Page layout structure is a set of HTML elements and css classes making up the over-all look and feel of the page frame in corporate a theme.

==== Server core components

Core server components are:

WebServices:: WebServices exchange XML with a client's DataProvider. <<DocXmlData,WrsServlet>> is the default service for data model requests.
BindingSets:: BindingSets translate between the logical data model of a BCD-UI application and the physical databases and control access to the data.
WebServices use <<DocBinding,bindings>> to create the appropriate SQL for data reading and writing.
Servlets:: Several servlets provide all kinds of services to BCD-UI clients.
BCD-UI servlets are usually not addressed from users of BCD-UI directly.
Servlets are listed <<DocFilter,here.>>
Filter:: Filter control the traffic from and to the server under different aspects as security and caching.
Filters are listed <<DocFilter,here.>>

==== Delivered sources

Because BCD-UI applications are Jakarta EE applications, most artifacts are typical Jakarta EE elements.
BCD-UI is delivered in the form of

Jakarta EE Server components:: Servlets and ServletFilters fulfilling server side tasks, for example access right evaluation or file upload.
WebServices:: WebServices serve for XML exchange with the client mainly for database access.
JavaScript library:: JavaScript code forms the base for the client-side controller of the standard Model/View/Control pattern.
JSP tag library:: JSP tags are wrappers of the JavaScript functionality to ease their use on JSP pages. Usage of JSP is optional.
XSLT library:: XSLT forms the base of views of the standard Model/View/Control pattern.
Configuration files:: Configuration XML files allow to modify the behaviour of BCD-UI's components.

Each artifact can be extended or replaced by custom-written Java, and Javascript implementing the given interfaces.
