[[DocDebug]]
== Debugging

=== Support for debugging

Unzip the gui status:: To see the guiStatus used in requests in their uncompressed form, send it as `data` parameter to the ZipLet servlet. For example: `http://localhost:8080/webApp/bcdui/servlets/ZipLet?data=z2e-f7xPr3FQumlE...`
Monitor network traffic:: Eclipse "TCP/IP Monitor" view as well as highly recommended link:https://www.telerik.com/fiddler[Fiddler^] tool can server as proxies to monitor network traffic exchanged between browser and server.
Server side logging:: log4j2.xml file in call path allows fine-grained control of server side logging. Per default this is found in the /src/java folders of the template applications.
Endless waiting renderers:: use  `bcdui.factory.objectRegistry.getWaitingIds()`  to detect ids of renderer/wrapper, waiting for yet non-existing ids.
Find out which BindingItems a binding set has:: de.businesscode.bcdui.binding.Bindings.getInstance().get("b4_bsg_tte", java.util.Arrays.asList("cage_dy"))
Read information about a specific BindingItem::
[source,javascript]
----
de.businesscode.bcdui.binding.Bindings.getInstance()
    .get("b4_bsg_tte", java.util.Arrays.asList("cage_dy"))
    .get("cage_dy")
    .getJDBCDataTypeName()
----
Use the browser developer console to examine client issues:: All modern browser have a console, where you can execute issue JavaScript commands to examine object status
Use request parameter debug=true:: The debug request parameter makes the application more picky about JavaScript parameters and turns on client logging that might help.

=== Common error messages

ERROR - Internal stylesheet error. this['node-set']= function (x) { return x; } 0 0 Unzip gui status:: This error message occurs if an import of a stylesheet fails inside a stylesheet. The nodeset function is usually the first line after the `include` statement
IE: An Invalid character was found in text content. Or: Switch from current encoding to specified encoding not supported.:: Wrong encoding im xsl:output
Mozilla FireFox::
In general use IE tfor debugging XSLT, it will give better error messages. +
One thing specific about Mozilla: If your stylesheet's output produces multiple top-level elements (which is not allowed), Firefox does not throw an error like IE for the same output but wrap the output into an artificial root element instead.
IE: stack overflow at line: 0:: Is often related to an IE caching issue, in many cases it goes away with caching being enabled.
