[[DocGettingStarted]]
== Getting Started

At its core, a BCD-UI application is a standard Jakarta EE web application.
For the following, we assume you already have a blank application running.

If you are not an experienced Java web application developer, make sure you have a plain Java web application running before you turn it into a BCD-UI application. +

TIP: If you don't know how to make a vanilla application running with your IDE and Tomcat, check the <<DocBootstrap,Bootstrap>> chapter.

To turn a plain into a BCD-UI application, just do these 4 steps, detailed out in <<DocAppsetup,Application Setup>>, to turn it into a BCD-UI application

* Add bcd-ui-core.jar and bcd-ui-theme.jar, and their dependencies
* Copy some entries into your web.xml
* Define database connection and default in context.xml
* Add log4j2.xml

and you are read to go.

==== Required knowledge
Target audience of this tutorial are developers already developing Java web applications. You should already be able to

// Store link in a var because underscores need special handling
:xslt-deep-link: https://edutechwiki.unige.ch/en/XSLT_Tutorial_-_Basics

. Create and understand Java Jakarta web applications https://happycoding.io/tutorials/java-server/[intro, window="_blank"]
. Run Tomcat together with you favorite IDE, for example https://www.baeldung.com/eclipse-tomcat[with Eclipse, window="_blank"]
. Operate a standard SQL database and have some tables with data, for example https://www.postgresqltutorial.com/[Postgres, window="_blank"]
. Know how to use https://developer.mozilla.org/en-US/docs/Web/JavaScript[JavaScript, window="_blank"]
. Have an understanding of HTML, css, XML, Ajax
. Be able to read and write XPath https://www.w3schools.com/xml/xpath_intro.asp[into, window="_blank"] and XSLT https://www.w3schools.com/xml/xsl_intro.asp[short, window="_blank"] or {xslt-deep-link}[in depth, window="_blank"]

Let's continue by creating our <<DocSimpleReq,first page>> with BCD-UI.
