[[DocGettingStarted]]
== Getting Started

To start developing with BCD-UI, just follow these steps:

Set up your development environment ::
  * Get Java >=11, your favorite IDE and a Jakarta EE web server like Tomcat up and running
  * Have a look at  <<DocBootstrap,Bootstrap>> on how to improve Eclipse support for BCD-UI by importing config some BCD-UI specific files.

Set up a web application using BCD-UI::
  * Create a standard web application with your IDE, test it
  * Add bcd-ui-core.jar and bcd-ui-theme.jar to your dependencies
  * Copy some entries into your web.xml
  * Define database connection and default in context.xml

This is all. See chapter <<DocAppsetup,Application Setup>> for these steps. There we also discuss the internal layout of BCD-UI jar files.

Add pages to your web application ::
  * BCD-UI pages are just plain standard HTML pages, and a single bcdui.js file being loaded
  * See chapter <<DocSimpleReq,Simple request>> or <<DocMinimalCube,Minimal Cube>> for this

=== Step by step

Once your application is set up following <<DocAppsetup,Application Setup>>, you can start developing.

==== Create Simple Request Page

Let's continue by creating our <<DocSimpleReq,first page>> with BCD-UI.
