[[DocSecurity]]
== Security

=== Security Overview

BCD-UI supports security with the following features

* https:// hosting, partly or complete
* Company authentication and authorization mechanisms like central LDAP and single login can be applied
* SQL injection prevention
* no-cache no-store to protect secure data on shared computers, see <<DocCaching,caching>>
* Integration of link:https://shiro.apache.org/[Apache Shiro^] access rules
* Easy declarative user rights for:
 ** <<DocBinding,BindingSets>>
   *** Restrict write access
   *** Advanced row-level security support for all databases
   *** Trigger additional actions when writing to a BindingSet, including keeping a history of data changes
 ** <<DocWidgets,Menu>> structure shown to the user, for example whether admin pages are offered for navigation,
   see @rights attribute in link:https://github.com/businesscode/BCD-UI/blob/master/Docu/xsd/menu-1.0.0.xsd[menu-1.0.0.xsd^]
* Windows single-sign-on for EnterpriseEdition

=== Security access filter

A security access filter serves as the central entry point to the application and validates each access against the security policy.
Each request is checked whether it addresses a

* Public resource: Not in scope of the filter, the filter will let the request through
* Protected resource
 ** Accessed in a valid session: The filter will let the request through
 ** No valid session but auto-login: Auto-login is available through the use of HTTP cookies.
 ** No valid session: The filter will re-direct the request to the login page to establish a valid session with a valid login.

After login, the original request is processed.

For each url path you can also set required rights in the shiro.ini file.

==== Developer view

Developers need to follow these rules to implement secure applications:

* Enable ShiroFilter security filter in web.xml to enforce login for non-public areas
* Configure the CachingFilter to send user dependent and sensitive data with `no-cache`
* Invalidate sessionId on log-off and session timeout explicitly
* The system supports deep links, i.e. redirecting to the originally requested page after login +
icon:paperclip[] The system uses the first unsuccessfully access url for redirection.
Make sure all resources addressed from the public login page are also public, otherwise the user is forwarded to that
resource (often a .css file) after the successful login attempt in, when the target was the login page.

==== Shiro permissions

The Shiro _subject_ of the current session represents the user in the system.
Rights can be queried via `SecurityUtils.getSubject().isPermitted(value)`.
Apache Shiro, supports a hierarchical permission structure and wild-cards in the hierarchy.
For example one user may only be allowed `page:report:scorecard` where else another user may be granted
access to all pages  `page:*` .

==== Login form and logging

. Login page +
A login page is a standard page with two plain inputs:
+
[source,html,indent=0]
----
include::../web/login.html[tag=inputs]
----
Per default bcdui static resources are accessible without login, you can also use BCD-UI buttons if you want.

. Login logging +
By adding `bcd_log_login` BindingSet to your application, all login attempts, and their result is logged into the corresponding table.

To set up users and their authorization, you can choose the simple setup by hard-coding them in shiro.ini, by maintaining them in BCD-UI's database or authenticated with oAuth (AD, Google, facebook etc) combined with rights maintained in your database.

==== Page access rights
No matter which method you use for defining users and their roles, use the [urls] section in shiro.ini to define access permissions needed for pages. It is easy to also adjust the menu to offer only allowed pages.

[source,xml,indent=0]
----
include::../web/WEB-INF/shiro.ini[tag=urls]
----
<1> Here we define that any authenticated user can access /cube
<2> For /api/** we require login and a 'pages:admin' permission


=== Define users in shiro.ini
You can have an easy shiro.ini - only setup in the following way:

.Add any users, their password and their roles:
[source,xml,indent=0]
----
include::../web/WEB-INF/shiro.ini[tag=users]
----

.Define permissions of roles:
[source,xml,indent=0]
----
include::../web/WEB-INF/shiro.ini[tag=roles]
----
Users with 'adminRole' also have the pages:admin right.

=== Define users in the database
Instead of having a static set of users and passwords in shiro.ini, you can store users and passwords in the database.

[source,xml,indent=0]
----
include::../web/WEB-INF/shiro.ini[tag=mainJdbcRealm]
----
Keep [users] and [roles] sections empty and follow for [urls] the description given in the chapter above.

=== SubjectSettings config
Add a file `WEB-INF/bcdui/subjectSettings.xml` with at least the following content:

.Switch on SubjectSettings
[source,xml,indent=0]
----
include::../web/WEB-INF/bcdui/subjectSettings.xml[]
----
Later you can define BindingSet related security restrictions here as described
in <<DocBinding,BindingSet Features / Row-Level-Security>>

=== User related BindingSets
Add bcd_sec_user and bcd_sec_user_settings BindingSets (and the corresponding tables).
There is no prebuilt UI editor for these two tables, but their content should be self-explanatory.
All attributes and permissions assigned to a user in the table corresponding to `bcd_sec_user_settings` are read when the user logs in.
These become in-memory subject settings, which can be used to query whether a user has a certain permission.
These permissions are checked for example by the security filter when accessing an url.

=== Custom setup +
You may also provide your own LoginServlet or Realm for a custom setup of deriving users and their attributes.
Please check Shiro documentation for more options.

=== OAuth2 with Azure / Google etc

BCD-UI provides Shiro integrated implementation for general OAuth2 authentication (referred to as oauth in this docu) and ready-to-use modules for Azure and Google integration. +
Authentication is handled by OAuth, permissions are managed by application through _SubjectSettings_.

. Prerequisites
.. Register your client application to Azure/Google/x to obtain a client and a client secret. For Google, we use 'email' scope and for Azure `https://graph.microsoft.com/user.read`, but you can override this and use whatever you prefer to use for authentication.

. Configuration
+
The shiro.ini link:https://github.com/businesscode/BCD-UI/blob/master/Server/configFiles/WebContent/WEB-INF/shiro.ini[template of BCD-UI] describes the setup, more about this the following section
+
.oAuth sample with Azure
[source]
----
include::../web/WEB-INF/shiro.ini[tag=oAuth,indent=0]
----
The mentioned template shiro.xml also describes oAuth with Google and how to combine multiple providers,

=== Kerberos / Windows SSO / Windows Authentication

BCDUI also provides transparent integration for authentication against Windows Active Directory (or any other Directory service) via Kerberos protocol.
This is supported by the Enterprise Edition of BCD-UI, please contact BusinessCode GmbH for questions.
