[[UserBeans]]
== Subject Preferences

Subject preferences are name/value pairs which can be set client sided.
To activate the feature, you need the following:


1) add the SubjectPreferencesRealm realm to your shiro.ini

[main]
realmSubjectPreferences = de.businesscode.bcdui.subjectsettings.SubjectPreferencesRealm
securityManager.realms = .... $realmSubjectPreferences

2) map SubjectPreferences servlet in web.xml
[source,xml]
  <servlet>
    <servlet-name>bcdui4.SubjectPreferences</servlet-name>
    <servlet-class>de.businesscode.bcdui.web.servlets.SubjectPreferences</servlet-class>
    <init-param>
      <param-name>cookieMaxAge</param-name>
      <param-value>31536000</param-value>
    </init-param>
    <load-on-startup>1</load-on-startup>
  </servlet>
  <servlet-mapping>
    <servlet-name>bcdui4.SubjectPreferences</servlet-name>
    <url-pattern>/bcdui/servlets/SubjectPreferences/*</url-pattern>
  </servlet-mapping>

3) add a /bcdui/conf/subjectPreferences.xml configuration file
[source,xml]
<?xml version="1.0" encoding="UTF-8"?>
<sec:SubjectPreferencesConfig xmlns:sec="http://www.businesscode.de/schema/bcdui/subjectsettings-1.0.0" cookieName="bcdSubjectPreferences" cookiePath="/bcdui">
  <sec:Settings>
    <sec:Setting name="allowed_preference_name_1">
      <sec:SourceSetting ref="referenced_user_permission" isMulti="true|false" defaults="yourdefault1,yourdefault2"/>
    </sec:Setting>
    <sec:Setting name="name="allowed_preference_name_2">
      <sec:Values isMulti="true|false" preventEmpty="true|false">
        <sec:Value>allowed_value_1</sec:Value>
        <sec:Value default="true|false">allowed_value_2</sec:Value>
      </sec:Values>
    </sec:Setting>
  </sec:Settings>
</sec:SubjectPreferencesConfig>

=== Usage:

To set/update a subject permission, you can either call mapped SubjectPreferences servlet with name and value attributes in a POST request (multiple values -if allowed- can be separated by comma),
or you use a WRS request with wrs:I/M/D rows to insert/modify/delete entries. The WRS consists of (at least) two columns with the names right_name and right_value.
A GET request to the servlet returns you a 3 column WRS which lists all currently allowed values. The 3rd column holds true if the right is active at the moment.

Each sec:Setting node in your config describes one allowed attribute which you can set. To define the allowed values
for that named permission, you can either give a list of static well known values (sec:Values/sec:Value) or you reference
a user based permission via sec:SourceSetting. You can not do self-referencing here. sec:Values/sec:SourceSetting may have an attribute "isMulti"
which -when set to true- allows you to set multiple values. For this, the servlet call needs to separate the single values by comma.


==== Default Values:

If you haven't set any subject preference yet and want to access it, a default value is chosen and returned (if available).
This is the value from the sec:Values list which is marked as default with the "default='true'" attribute. In case of an allowed multi
setting, you can have multiple defaults. For sec:SourceSetting based entries, you can use the defaults attribute to give a comma separated
string of default values. #bcdAllAllowed# can be used to set all allowed values as default.
When you remove the last entry of a setting, it stays empty, when you have emptyAllowed="true" specified. Otherwise, the default
value(s) is/are restored.
If you modify the list by doing a POST operation, the values are manifested in a cookie if you specified a cookieName on config root.
Optionally you can also change the cookiePath. When it comes to filling not yet set preferences, cookie values are taken over default values.

==== URL Usage:

If your setting is prefixed with "bcdClient:", you can reuse it in an URL, like "http://localhost:8080/myApp/${bcdClient:pageId}/index.html".
The expression is replaced with the value and forwarded. Of course multiple expressions are possible. A value of "*" will be replaced with an
empty string, in case the url then holds "//" somewhere, this will be cleaned up to "/". Ensure that the url is excluded from caching, otherwise
you'd have to hit F5 after switching the value and accessing the page.

==== Client Visibility:

In general, "bcdClient:" prefixed values are visible on client side by accessing "bcdui.config.clientRights".

==== Read/Write security:

Set subject preferences can be also used for server sided read/write protection (see SubjectSettings).
For this, you can define a SubjectFilterType as you know it from subject settings.

Example:

[source,xml]
  <SubjectFilterType name="bcdUserBean:country">
    <Caption>country via bcdUserBean</Caption>
    <BindingItems>
      <C bRef="country"/>
    </BindingItems>
  </SubjectFilterType>

And in a binding you can reference it the usual way then. `allowed:allWrite` can be any right type you defined.

[source,xml]
  <SubjectSettings>
   <Security><Operation permission="allowed:allWrite" name="write"/></Security>
    <SubjectFilters>
      <SubjectFilter type="bcdUserBean:country"/>
    </SubjectFilters>
  </SubjectSettings>

=== i18n Language switch:

bcdui.i18n.switchLanguage function requires the upper mechanism (realm/web.xml/config) to be enabled
and a <sec:Setting name="bcd_i18n:lang"> needs to be defined in your config with suitable allowed values.

==== Setting a value programmatically:

[source,java]
import de.businesscode.bcdui.web.servlets.SubjectPreferences;
SubjectPreferences.setPermission("bcdLimit:country", "DE");